### PR TITLE
Run build workflow under GHA container

### PR DESCRIPTION
**Pull request by keynslug**
Also tune PKGBUILD a bit before making a package:
1. Disable verbose cmake output.
2. Disable emitting debuginfo, which makes builds noticeably faster and wastes much less disk space.

Supposedly, this should not affect resulting build artifacts, which are stripped of debug symbols anyway.

### CODE REVIEW

**Comment by keynslug** [comment]
Example of successful workflow run.
https://github.com/keynslug/archbuilder-telegram-desktop-userfonts/actions/runs/8365806473

**Comment by AndydeCleyre** [comment]
Thanks! I'll have to look at this closely, it looks like a total workflow rewrite and I'm not yet sure why each part needed replacing.

If I take the PKGBUILD changes I'll probably put those directly in the AUR repo, rather than editing the PKGBUILD on the fly here.

I probably will switch to using Podman, though I'd rather find out why and fix [buildah no longer working for the purpose](https://github.com/containers/buildah/discussions/5356). But it's been weeks with no more insight from the buildah team, so . . . that may not happen.

**Comment by AndydeCleyre** [comment]
I'm going to try to (at least first) *just* port it from buildah to the GHA container system, changing as little else as possible.

**Comment by AndydeCleyre** [comment]
Hopefully I've just about got this building and releasing again. The last *build* part of the build was successful, but had a problem afterward (I think the glob was catching two lines, matching the new debug package as well).

After porting to GHA containers instead of buildah, as you demonstrated, I merged one of your commits from here, and did indeed update the pkgbuild directly to reduce the size, as builds were running out of space. Thanks so much! I also ported to newer actions, as you suggested -- I couldn't merge the relevant commits because they changed too many other things as well.

If it's working (currently waiting on the build . . .) and you think other changes from here are still worthwhile, you're very welcome to submit PRs, but please make them more scope-limited for easier merging. Thanks again for the help!

**Comment by keynslug** [comment]
> you think other changes from here are still worthwhile

Not really, it's perfectly fine to just leave them out (or apply elsewhere, as with this PKGBUILD patch). Glad that you've got it working again. Thanks!

**Pull request closed without merging**
